---
apiVersion: v1
kind: Template
metadata:
  name: pyrra-test
objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: pyrra-kubernetes
  rules:
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - prometheusrules
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - prometheusrules/status
    verbs:
    - get
  - apiGroups:
    - pyrra.dev
    resources:
    - servicelevelobjectives
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - pyrra.dev
    resources:
    - servicelevelobjectives/status
    verbs:
    - get
    - patch
    - update
  - apiGroups: [""]
    resources:
    - configmaps
    verbs:
    - create
    - get
    - list
    - update
    - watch
    - patch
  - apiGroups: [""]
    resources:
    - namespaces
    verbs:
    - get
    - list
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      service.beta.openshift.io/inject-cabundle: "true"
    labels:
      app.kubernetes.io/name: pyrra-api
    name: pyrra-api
    # namespace: openshift-monitoring
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/name: pyrra-api
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app.kubernetes.io/name: pyrra-api
      spec:
        containers:
          - args:
              - api
              - --prometheus-url=https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091
              - --api-url=http://pyrra-kubernetes.openshift-monitoring.svc.cluster.local:9444
              - --prometheus-bearer-token-path=/var/run/secrets/tokens/pyrra-kubernetes
            image: ${IMAGE}:${RELEASE}
            imagePullPolicy: IfNotPresent
            name: pyrra-api
            ports:
              - containerPort: 9099
                name: http
                protocol: TCP
            resources:
              limits:
                cpu: 100m
                memory: 30Mi
              requests:
                cpu: 100m
                memory: 20Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /var/run/secrets/tokens
                name: pyrra-sa-token
                readOnly: true
              - mountPath: /etc/ssl/certs
                name: trusted-ca
                readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        serviceAccountName: pyrra-kubernetes
        volumes:
          - name: pyrra-sa-token
            projected:
              sources:
                - serviceAccountToken:
                    path: pyrra-kubernetes
          - configMap:
              defaultMode: 420
              items:
                - key: service-ca.crt
                  path: service-ca.crt
              name: openshift-service-ca.crt
            name: trusted-ca
- apiVersion: v1
  metadata:
    name: pyrra-kubernetes
    # namespace: openshift-monitoring
    labels:
      app.kubernetes.io/name: pyrra-kubernetes
  spec:
    ports:
    - name: internal
      port: 9443
    - name: api
      port: 9444
    selector:
      app.kubernetes.io/name: pyrra-kubernetes
  kind: Service
- apiVersion: apps/v1
  metadata:
    name: pyrra-kubernetes
    # namespace: openshift-monitoring
    labels:
      app.kubernetes.io/name: pyrra-kubernetes
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: pyrra-kubernetes
    replicas: 1
    template:
      metadata:
        labels:
          app.kubernetes.io/name: pyrra-kubernetes
      spec:
        serviceAccountName: pyrra-kubernetes
        containers:
        - args:
          - kubernetes
          image: ${IMAGE}:${RELEASE}
          name: pyrra-kubernetes
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
  kind: Deployment
# - apiVersion: apps/v1
#   metadata:
#     name: pyrra-kubernetes
#     # namespace: openshift-monitoring
#     labels:
#       app.kubernetes.io/name: pyrra-kubernetes
#   spec:
#     selector:
#       matchLabels:
#         app.kubernetes.io/name: pyrra-kubernetes
#     replicas: 1
#     template:
#       metadata:
#         labels:
#           app.kubernetes.io/name: pyrra-kubernetes
#       spec:
#         serviceAccountName: pyrra-kubernetes
#         containers:
#         - args:
#           - kubernetes
#           image: ${IMAGE}:${RELEASE}
#           name: pyrra-kubernetes
#           resources:
#             limits:
#               cpu: 100m
#               memory: 30Mi
#             requests:
#               cpu: 100m
#               memory: 20Mi
#   kind: Deployment
# - apiVersion: apps/v1
#   metadata:
#     name: pyrra-kubernetes
#     # namespace: openshift-monitoring
#     labels:
#       app.kubernetes.io/name: pyrra-kubernetes
#   spec:
#     selector:
#       matchLabels:
#         app.kubernetes.io/name: pyrra-kubernetes
#     replicas: 1
#     template:
#       metadata:
#         labels:
#           app.kubernetes.io/name: pyrra-kubernetes
#       spec:
#         serviceAccountName: pyrra-kubernetes
#         containers:
#         - args:
#           - kubernetes
#           image: ${IMAGE}:${RELEASE}
#           name: pyrra-kubernetes
#           resources:
#             limits:
#               cpu: 100m
#               memory: 30Mi
#             requests:
#               cpu: 100m
#               memory: 20Mi
#   kind: Deployment
- apiVersion: v1
  metadata:
    name: pyrra-kubernetes
    # namespace: openshift-monitoring
  kind: ServiceAccount
- apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: pyrra-kubernetes
    # namespace: openshift-monitoring
  subjects:
  - kind: ServiceAccount
    name: pyrra-kubernetes
    # namespace: openshift-monitoring
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: pyrra-kubernetes
  kind: ClusterRoleBinding
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: cluster-monitoring-view
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-monitoring-view
  subjects:
    - kind: ServiceAccount
      name: pyrra-kubernetes
      # namespace: openshift-monitoring
parameters:
- name: IMAGE
  value: ghcr.io/pyrra-dev/pyrra
- name: RELEASE
  value: v0.4.4